services:
  db:
    image: postgres
    container_name: sipos-motorservice-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: kutyagumi
      POSTGRES_DB: motorservice
    volumes:
      - postgres_data:/var/lib/postgresql
volumes:
  postgres_data: